import Header from './Header';
import Footer from './Footer';
import FooterCTA from './FooterCTA'
import HomeTestimonial from './HomeTestimonial';
import SupportedDivices from './SupportedDivices';
import Home_B_Hero from './Home_B_Hero';
import WelcomeBannerGrids from './WelcomeBannerGrids';
import FeaturesGrid from './FeaturesGrid';
import Home_A_Hero from './Home_A_Hero';
import Home_A_Grids from './Home_A_Grids';
import Navigation from './Navigation';
import InnerPageTitleBlock from './InnerPageTitleBlock';
import InvestorsBlock from "./InvestorsBlock";
import OurJourneyBlock from './OurJourneyBlock';
import OurTeam from './OurTeam';
import VisionAndMission from './VisionAndMission';
import PricingPlans from './PricingPlans';

export { Header,Footer,FooterCTA,HomeTestimonial,SupportedDivices,Home_B_Hero,WelcomeBannerGrids,FeaturesGrid,Home_A_Hero,Home_A_Grids,Navigation,InnerPageTitleBlock,InvestorsBlock,OurJourneyBlock,OurTeam,VisionAndMission,PricingPlans }